//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/BB_V3/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::E5, // Injector 1
	Gpio::E6, // Injector 2
	Gpio::E0, // Injector 3
	Gpio::C13, // Injector 4
	Gpio::E1, // Injector 5
	Gpio::A15, // Injector 6
	Gpio::A7, // Injector 7
	Gpio::B8, // Injector 8
	Gpio::E8, // Boost controler
	Gpio::E9, // Idle valve 1
	Gpio::E12, // Tacho output
	Gpio::E11, // Low side output 1
	Gpio::E10, // Low side output 2
	Gpio::E13, // Low side output 3
	Gpio::E14, // Fan output
	Gpio::E15, // Fuel pump output
	Gpio::B14, // DBW_PWM
	Gpio::D3, // DBW_DIS
	Gpio::D0, // DBW_DIR
	Gpio::B9, // Ignition 1
	Gpio::B6, // Ignition 2
	Gpio::B7, // Ignition 3
	Gpio::B3, // Ignition 4
	Gpio::B5, // Ignition 5
	Gpio::D1, // Ignition 6
	Gpio::D4, // Ignition 7
	Gpio::D7, // Ignition 8
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "Boost controler",
// "Idle valve 1",
// "Tacho output",
// "Low side output 1",
// "Low side output 2",
// "Low side output 3",
// "Fan output",
// "Fuel pump output",
// "DBW_PWM",
// "DBW_DIS",
// "DBW_DIR",
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Ignition 5",
// "Ignition 6",
// "Ignition 7",
// "Ignition 8",
}
