//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/BB_V3/connectors/main.yaml
#pragma once

#define PIN_1 E5
#define PIN_2 E6
#define PIN_3 E0
#define PIN_4 C13
#define PIN_5 E1
#define PIN_6 A15
#define PIN_7 A7
#define PIN_8 B8
#define PIN_9 E8
#define PIN_10 E9
#define PIN_11 E12
#define PIN_12 E11
#define PIN_13 E10
#define PIN_14 E13
#define PIN_15 E14
#define PIN_16 E15
#define PIN_17 B14
#define PIN_18 D3
#define PIN_19 D0
#define PIN_20 B9
#define PIN_21 B6
#define PIN_22 B7
#define PIN_23 B3
#define PIN_24 B5
#define PIN_25 D1
#define PIN_26 D4
#define PIN_27 D7
#define PIN_28 EFI_ADC_15
#define PIN_29 EFI_ADC_0
#define PIN_30 EFI_ADC_1
#define PIN_31 EFI_ADC_10
#define PIN_32 EFI_ADC_11
#define PIN_33 EFI_ADC_12
#define PIN_34 EFI_ADC_13
#define PIN_35 EFI_ADC_4
#define PIN_36 EFI_ADC_5
#define PIN_37 EFI_ADC_6
#define PIN_38 EFI_ADC_14
#define PIN_39_event_inputs A10
#define PIN_39_switch_inputs A10
#define PIN_40_event_inputs A9
#define PIN_40_switch_inputs A9
#define PIN_41_event_inputs A8
#define PIN_41_switch_inputs A8
#define PIN_42_event_inputs D8
#define PIN_42_switch_inputs D8
#define PIN_43_event_inputs D10
#define PIN_43_switch_inputs D10
