//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/BB_V2/connectors/main.yaml
#pragma once

#define PIN_1 D12
#define PIN_2 D13
#define PIN_3 D14
#define PIN_4 D15
#define PIN_5 E9
#define PIN_6 E11
#define PIN_7 E14
#define PIN_8 E13
#define PIN_9 C6
#define PIN_10 C7
#define PIN_11 C13
#define PIN_12 D3
#define PIN_13 E12
#define PIN_14 E6
#define PIN_15 E3
#define PIN_16 B12
#define PIN_17 D3
#define PIN_18 B14
#define PIN_19 E4
#define PIN_20 D5
#define PIN_21 D7
#define PIN_22 B9
#define PIN_23 A8
#define PIN_24 D10
#define PIN_25 D9
#define PIN_26 D11
#define PIN_27 D8
#define PIN_28 E8
#define PIN_29 EFI_ADC_15
#define PIN_30 EFI_ADC_0
#define PIN_31 EFI_ADC_1
#define PIN_32 EFI_ADC_10
#define PIN_33 EFI_ADC_11
#define PIN_34 EFI_ADC_12
#define PIN_35 EFI_ADC_13
#define PIN_36 EFI_ADC_14
#define PIN_37 EFI_ADC_9
#define PIN_38_event_inputs E1
#define PIN_38_switch_inputs E1
#define PIN_39_event_inputs E0
#define PIN_39_switch_inputs E0
#define PIN_40_event_inputs D4
#define PIN_40_switch_inputs D4
#define PIN_41_event_inputs D6
#define PIN_41_switch_inputs D6
