//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/BB_V2/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D12, // Injector 1
	Gpio::D13, // Injector 2
	Gpio::D14, // Injector 3
	Gpio::D15, // Injector 4
	Gpio::E9, // Injector 5
	Gpio::E11, // Injector 6
	Gpio::E14, // Injector 7
	Gpio::E13, // Injector 8
	Gpio::C6, // Boost controler
	Gpio::C7, // Idle valve 1
	Gpio::C13, // Tacho output
	Gpio::D3, // Low side output 1
	Gpio::E12, // VVT output
	Gpio::E6, // Fan output
	Gpio::E3, // Fuel pump output
	Gpio::B12, // Low current output 1
	Gpio::D3, // Low side output 1
	Gpio::B14, // DBW_PWM
	Gpio::E4, // DBW_DIS
	Gpio::D5, // DBW_DIR
	Gpio::D7, // Ignition 1
	Gpio::B9, // Ignition 2
	Gpio::A8, // Ignition 3
	Gpio::D10, // Ignition 4
	Gpio::D9, // Ignition 5
	Gpio::D11, // Ignition 6
	Gpio::D8, // Ignition 7
	Gpio::E8, // Ignition 8
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "Boost controler",
// "Idle valve 1",
// "Tacho output",
// "Low side output 1",
// "VVT output",
// "Fan output",
// "Fuel pump output",
// "Low current output 1",
// "Low side output 1",
// "DBW_PWM",
// "DBW_DIS",
// "DBW_DIR",
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Ignition 5",
// "Ignition 6",
// "Ignition 7",
// "Ignition 8",
}
