//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/M54PNP/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A14: return "Camshaft Sensor";
		case Gpio::A15: return "Crankshaft Sensor";
		case Gpio::A8: return "Inj/ign relay";
		case Gpio::B0: return "DBW_DIS";
		case Gpio::B1: return "DBW_DIR";
		case Gpio::B12: return "VANOS INTAKE";
		case Gpio::B13: return "VANOS EXHAUST";
		case Gpio::B14: return "IDLE VALVE 1";
		case Gpio::B15: return "THERMOSTAT";
		case Gpio::B9: return "Clutch sensor";
		case Gpio::C6: return "Injector 5";
		case Gpio::C7: return "Injector 6";
		case Gpio::C9: return "Main relay";
		case Gpio::D10: return "Boost controler";
		case Gpio::D11: return "Fuel pump output";
		case Gpio::D12: return "Injector 1";
		case Gpio::D13: return "Injector 2";
		case Gpio::D14: return "Injector 3";
		case Gpio::D15: return "Injector 4";
		case Gpio::D3: return "Spare trigger input";
		case Gpio::D4: return "VSS";
		case Gpio::D5: return "Digital Input 1";
		case Gpio::D6: return "BRAKE pedal input";
		case Gpio::D8: return "IDLE VALVE 2";
		case Gpio::D9: return "Fan output";
		case Gpio::E0: return "FLEX sensor";
		case Gpio::E10: return "Ignition 5";
		case Gpio::E11: return "Ignition 6";
		case Gpio::E12: return "Ignition 4";
		case Gpio::E13: return "Ignition 3";
		case Gpio::E14: return "Ignition 2";
		case Gpio::E15: return "Ignition 1";
		case Gpio::E7: return "DBW_PWM";
		case Gpio::E8: return "INTAKE VALVE";
		default: return nullptr;
	}
	return nullptr;
}
