//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/M54PNP/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D12, // Injector 1
	Gpio::D13, // Injector 2
	Gpio::D14, // Injector 3
	Gpio::D15, // Injector 4
	Gpio::C6, // Injector 5
	Gpio::C7, // Injector 6
	Gpio::C9, // Main relay
	Gpio::A8, // Inj/ign relay
	Gpio::D10, // Boost controler
	Gpio::B13, // VANOS EXHAUST
	Gpio::B12, // VANOS INTAKE
	Gpio::D8, // IDLE VALVE 2
	Gpio::B14, // IDLE VALVE 1
	Gpio::B15, // THERMOSTAT
	Gpio::D9, // Fan output
	Gpio::D11, // Fuel pump output
	Gpio::E7, // DBW_PWM
	Gpio::B0, // DBW_DIS
	Gpio::B1, // DBW_DIR
	Gpio::E15, // Ignition 1
	Gpio::E14, // Ignition 2
	Gpio::E13, // Ignition 3
	Gpio::E12, // Ignition 4
	Gpio::E10, // Ignition 5
	Gpio::E11, // Ignition 6
	Gpio::E8, // INTAKE VALVE
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Main relay",
// "Inj/ign relay",
// "Boost controler",
// "VANOS EXHAUST",
// "VANOS INTAKE",
// "IDLE VALVE 2",
// "IDLE VALVE 1",
// "THERMOSTAT",
// "Fan output",
// "Fuel pump output",
// "DBW_PWM",
// "DBW_DIS",
// "DBW_DIR",
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Ignition 5",
// "Ignition 6",
// "INTAKE VALVE",
}
