# List of all the board related files.
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp
BOARDINC  = $(BOARD_DIR)

# Override DEFAULT_ENGINE_TYPE
DDEFS += -DSTM32F407xx
DDEFS += -DFIRMWARE_ID=\"M54PNP\"
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::Unassigned
DDEFS += -DHAL_TRIGGER_USE_PAL=TRUE
DDEFS += -DHAL_VSS_USE_PAL=TRUE

# Define the flash size for the board (This board has 512K STM32F407)
DDEFS += -DMIN_FLASH_SIZE=512

# STM32F407VET6: 512 KiB flash — drop ROM-heavy modules (full M54PNP on VG has more headroom).
DDEFS += -DEFI_LUA=FALSE
DDEFS += -DEFI_LUA_LOOKUP=FALSE
# Embedded TunerStudio INI in firmware; without it, use TS project + connect over USB/serial/CAN as usual.
DDEFS += -DEFI_EMBED_INI_MSD=FALSE
DDEFS += -DEFI_TOOTH_LOGGER=FALSE
DDEFS += -DEFI_LOGIC_ANALYZER=FALSE
DDEFS += -DEFI_ENGINE_SNIFFER=FALSE
DDEFS += -DEFI_DYNO_VIEW=FALSE
DDEFS += -DEFI_WIDEBAND_FIRMWARE_UPDATE=FALSE
DDEFS += -DEFI_BLUETOOTH_SETUP=FALSE

# Enable specific features for the board
DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=100

# TS_SECONDARY_UxART_PORT
DDEFS += -DSTM32_SERIAL_USE_USART3=TRUE -DSTM32_UART_USE_USART3=FALSE
DDEFS += -DTS_SECONDARY_UxART_PORT=SD3 -DEFI_TS_SECONDARY_IS_SERIAL=TRUE
