//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/CoreECU/connectors/main.yaml
#pragma once

#define PIN_1 D12
#define PIN_2 D13
#define PIN_3 D14
#define PIN_4 D15
#define PIN_5 C6
#define PIN_6 C7
#define PIN_7 C9
#define PIN_8 A8
#define PIN_9 D10
#define PIN_10 B13
#define PIN_11 B12
#define PIN_12 D8
#define PIN_13 B14
#define PIN_14 B15
#define PIN_15 D9
#define PIN_16 D11
#define PIN_17 E7
#define PIN_18 B0
#define PIN_19 B1
#define PIN_20 E15
#define PIN_21 E14
#define PIN_22 E13
#define PIN_23 E12
#define PIN_24 E11
#define PIN_25 E10
#define PIN_26 E9
#define PIN_27 E8
#define PIN_28 EFI_ADC_14
#define PIN_29 EFI_ADC_0
#define PIN_30 EFI_ADC_1
#define PIN_31 EFI_ADC_10
#define PIN_32 EFI_ADC_11
#define PIN_33 EFI_ADC_12
#define PIN_34 EFI_ADC_13
#define PIN_35 EFI_ADC_4
#define PIN_36 EFI_ADC_5
#define PIN_37 EFI_ADC_6
#define PIN_38 EFI_ADC_7
#define PIN_39_event_inputs A14
#define PIN_39_switch_inputs A14
#define PIN_40_event_inputs A15
#define PIN_40_switch_inputs A15
#define PIN_41_event_inputs D4
#define PIN_41_switch_inputs D4
#define PIN_42_event_inputs D3
#define PIN_42_switch_inputs D3
#define PIN_43 EFI_ADC_15
#define PIN_44 B9
#define PIN_45 E0
#define PIN_46 D5
#define PIN_47 D6
