//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/KRYPTON/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D2, // Injector 1
	Gpio::C12, // Injector 2
	Gpio::C8, // Injector 3
	Gpio::C7, // Injector 4
	Gpio::C6, // Injector 5
	Gpio::D15, // Injector 6
	Gpio::D14, // Injector 7
	Gpio::D13, // Injector 8
	Gpio::D11, // Boost controler
	Gpio::D8, // Low side output 1
	Gpio::D9, // Tacho output
	Gpio::B12, // Low side output 2
	Gpio::B11, // Low side output 3
	Gpio::B10, // Low side output 4
	Gpio::D10, // Fan output
	Gpio::D12, // Fuel pump output
	Gpio::C3, // WBO_HEATER
	Gpio::E15, // Ignition 1
	Gpio::E14, // Ignition 2
	Gpio::E13, // Ignition 3
	Gpio::E12, // Ignition 4
	Gpio::E11, // Ignition 5
	Gpio::E10, // Ignition 6
	Gpio::E9, // Ignition 7
	Gpio::E8, // Ignition 8
// "Injector 1",
// "Injector 2",
// "Injector 3",
// "Injector 4",
// "Injector 5",
// "Injector 6",
// "Injector 7",
// "Injector 8",
// "Boost controler",
// "Low side output 1",
// "Tacho output",
// "Low side output 2",
// "Low side output 3",
// "Low side output 4",
// "Fan output",
// "Fuel pump output",
// "WBO_HEATER",
// "Ignition 1",
// "Ignition 2",
// "Ignition 3",
// "Ignition 4",
// "Ignition 5",
// "Ignition 6",
// "Ignition 7",
// "Ignition 8",
}
