//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/KRYPTON/connectors/main.yaml
#pragma once

#define PIN_1 D2
#define PIN_2 C12
#define PIN_3 C8
#define PIN_4 C7
#define PIN_5 C6
#define PIN_6 D15
#define PIN_7 D14
#define PIN_8 D13
#define PIN_9 D11
#define PIN_10 D8
#define PIN_11 D9
#define PIN_12 B12
#define PIN_13 B11
#define PIN_14 B10
#define PIN_15 D10
#define PIN_16 D12
#define PIN_17 C3
#define PIN_18 E15
#define PIN_19 E14
#define PIN_20 E13
#define PIN_21 E12
#define PIN_22 E11
#define PIN_23 E10
#define PIN_24 E9
#define PIN_25 E8
#define PIN_26 EFI_ADC_0
#define PIN_27 EFI_ADC_5
#define PIN_28 EFI_ADC_2
#define PIN_29 EFI_ADC_3
#define PIN_30 EFI_ADC_10
#define PIN_31 EFI_ADC_1
#define PIN_32 EFI_ADC_4
#define PIN_33 EFI_ADC_6
#define PIN_34 EFI_ADC_7
#define PIN_35 EFI_ADC_15
#define PIN_36 EFI_ADC_14
#define PIN_37_event_inputs E6
#define PIN_37_switch_inputs E6
#define PIN_38_event_inputs E5
#define PIN_38_switch_inputs E5
#define PIN_39_event_inputs E4
#define PIN_39_switch_inputs E4
#define PIN_40_event_inputs B9
#define PIN_40_switch_inputs B9
#define PIN_41_event_inputs E0
#define PIN_41_switch_inputs E0
#define PIN_42_event_inputs E2
#define PIN_42_switch_inputs E2
#define PIN_43_event_inputs E3
#define PIN_43_switch_inputs E3
