# List of all the board related files.
BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp
BOARDINC  = $(BOARD_DIR)

# Override DEFAULT_ENGINE_TYPE
DDEFS += -DSTM32F407xx
DDEFS += -DFIRMWARE_ID=\"CoreECU\"
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::Unassigned
DDEFS += -DHAL_TRIGGER_USE_PAL=TRUE
DDEFS += -DHAL_VSS_USE_PAL=TRUE

# Define the flash size for the board (This board has 512K STM32F407)
DDEFS += -DMIN_FLASH_SIZE=512

# Enable specific features for the board
DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=100

# TS_SECONDARY_UxART_PORT
DDEFS += -DSTM32_SERIAL_USE_USART3=TRUE -DSTM32_UART_USE_USART3=FALSE
DDEFS += -DTS_SECONDARY_UxART_PORT=SD3 -DEFI_TS_SECONDARY_IS_SERIAL=TRUE

# Lua size
DDEFS += -DLUA_USER_HEAP=32000
