# List of all the board related files.
BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp

# Override DEFAULT_ENGINE_TYPE

DDEFS += -DFIRMWARE_ID=\"APEX\"
IS_STM32F429 = yes

DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE
# TS_SECONDARY_UxART_PORT
DDEFS += -DSTM32_SERIAL_USE_USART2=TRUE -DSTM32_SERIAL_USART2_PRIORITY=7
DDEFS += -DTS_SECONDARY_UxART_PORT=SD2 -DEFI_TS_SECONDARY_IS_SERIAL=TRUE
# EGT chip
DDEFS += -DEFI_MAX_31855=TRUE

# 48K would not fit
# DDEFS += -DLUA_USER_HEAP=45000 need to be done in efifutures.h

